In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from mpl_toolkits import mplot3d
from matplotlib import cm
import mpl_toolkits.mplot3d.art3d as art3d

import os
import pandas as pd

matplotlib.rcParams['font.family'] = [ 'serif']
matplotlib.rcParams['agg.path.chunksize'] = 10000

In [2]:
import sys  
sys.path.insert(0, '/Users/Daniel/Documents/Research Projects/Cosmic Filaments/example_filaments')
import read_fils as rf

sys.path.insert(0, '/Users/Daniel/Documents/Research Projects/Cosmic Filaments/Filament_Metrics' )
import fil_metrics.metric_functions as fm 

skeleton_file_dm = '/Users/Daniel/Documents/Research Projects/Cosmic Filaments/example_filaments/del_galaxy.NDnet_s5.up.NDskl.BRK.a.NDskl'
filaments_dm = rf.ReadFilament(skeleton_file_dm)
filament_dm_dict = filaments_dm.filament_dict
print(filament_dm_dict) 

header1, ANDSKEL

ndims, 3

Comments, #No comments (RB)

Bounding box, BBOX [-9.46958,-11.2398,-10.2952] [19.1849,19.2268,23.9453]

ncrit, 142
nfils, 90
Reading data fields:
CP field: persistence_ratio

CP field: persistence_nsigmas

CP field: persistence

CP field: persistence_pair

CP field: parent_index

CP field: parent_log_index

CP field: log_field_value

CP field: field_value

CP field: cell

Filament field: field_value

Filament field: orientation

Filament field: cell

Filament field: log_field_value

Filament field: type

Reading filaments took 0.00 secs.
{'ncrit': 142, 'critical_points': [{'cp_idx': 3.0, 'px': 5.24243, 'py': 0.603427, 'pz': 6.55434, 'pair_ID': 29.0, 'boundary': 0.0, 'nfil': 3, 'destID,filID': [[49, 48], [67, 66], [70, 69]], 'Field Vals': [649.3622, 5.034659, 10623.39, 29.0, 2.0, 2.0, 4.026932, 10639.77, 19.0]}, {'cp_idx': 3.0, 'px': 5.72685, 'py': -3.57222, 'pz': 3.31045, 'pair_ID': 18.0, 'boundary': 0.0, 'nfil': 4, 'destID,filID': [[23, 12], [24, 13], [24, 

In [507]:
#separate 'filaments' and 'critical_points' dictionaries (each is now a list of dictionaries)
fils = filament_dm_dict['filaments'] 
crit_points = filament_dm_dict['critical_points'] 

In [4]:
#number of filaments
nfils = filament_dm_dict['nfils'] ; ncrit = filament_dm_dict['ncrit']
print("# of filaments: ",nfils,"\n","# of critical points :",ncrit)

# of filaments:  90 
 # of critical points : 142


In [5]:
#will NOT be using filpoints array (1d array) -- only using now to make gals array 
filpoints = fm.Fil_Coordinates1D(fils)
print(filpoints, "\n\n",np.shape(filpoints)) #425 coordinate points for filaments in this file

[[-2.81356  -2.00726  -1.79707 ]
 [-3.34829  -2.21085  -2.10106 ]
 [-3.55129  -2.20702  -2.52764 ]
 ...
 [ 0.287103  6.25466   1.18162 ]
 [ 0.284161  6.26514   1.18052 ]
 [ 0.28122   6.27562   1.17942 ]] 

 (425, 3)


In [6]:
#create "fake" galaxies
gals = filpoints * 1.5   ; gals = gals[::20] #multiplying filpoint values and slicing so we have fewer "galaxy" points
gals

array([[ -4.22034   ,  -3.01089   ,  -2.695605  ],
       [  1.080951  ,  -8.004285  ,   6.98871   ],
       [ -0.357204  ,  -0.59442   ,   1.20918   ],
       [ -0.4575405 ,   0.153831  ,  -1.805445  ],
       [  8.590275  ,  -5.35833   ,   4.965675  ],
       [  8.590275  ,  -5.35833   ,   4.965675  ],
       [ -4.17039   ,  -0.4638315 , -14.338515  ],
       [ -0.592353  ,   0.1898595 ,  -1.971945  ],
       [  6.21606   , -11.34813   ,   6.61596   ],
       [ -3.66426   ,  -4.813905  ,   4.56852   ],
       [ -0.07599075,   0.2026965 ,   1.158858  ],
       [  0.14864985,   4.59897   ,   0.9373755 ],
       [  0.413109  ,   7.533075  ,   2.32167   ],
       [  7.882215  ,   0.908364  ,   9.793755  ],
       [ -0.1563405 ,   3.314205  ,  -6.81822   ],
       [ -3.72741   ,   6.00546   ,   6.72939   ],
       [ -0.9740715 ,  11.24265   ,   3.995145  ],
       [  8.285175  ,   0.971172  ,  10.06425   ],
       [  5.72283   ,  -8.566665  ,   7.961805  ],
       [  6.228225  ,   1.33317

In [13]:
# CREATE DATAFRAME OF FILAMENT POINTS WHILE KEEPING FILAMENT ID -- INCLUDING SEGMENTS
df = pd.DataFrame()
for i in range(filament_dm_dict['nfils']):
    p = np.array(filament_dm_dict['filaments'][i]['px,py,pz'])
    p = np.hstack([p[:-1],p[1:]])
    p = pd.DataFrame(p,columns = ['px', 'py', 'pz','px2','py2','pz2'])
    p['Filament ID'] = i
    df = pd.concat([df, p])
df

px       py       pz       px2      py2      pz2  Filament ID
0  -2.813560 -2.00726 -1.79707 -3.348290 -2.21085 -2.10106            0
1  -3.348290 -2.21085 -2.10106 -3.551290 -2.20702 -2.52764            0
2  -3.551290 -2.20702 -2.52764 -3.547040 -2.07235 -2.75681            0
3  -3.547040 -2.07235 -2.75681 -3.620380 -2.03417 -2.75514            0
4  -3.620380 -2.03417 -2.75514 -3.937100 -2.23730 -2.73826            0
..       ...      ...      ...       ...      ...      ...          ...
5  -2.991490 -4.04842  2.25934 -2.875230 -3.97738  2.37498           87
0   6.295170 -4.11047  3.60174  6.229390 -4.13554  3.36975           88
1   6.229390 -4.13554  3.36975  6.179120 -4.20421  3.14064           88
0   0.287103  6.25466  1.18162  0.284161  6.26514  1.18052           89
1   0.284161  6.26514  1.18052  0.281220  6.27562  1.17942           89

[335 rows x 7 columns]

In [14]:
gal1 = gals[0]
gal1

array([-4.22034 , -3.01089 , -2.695605])

In [25]:
for i, j in df.iterrows():
    print(j['Filament ID'])

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
3.0
3.0
3.0
3.0
3.0
4.0
4.0
4.0
4.0
5.0
6.0
6.0
6.0
6.0
6.0
7.0
7.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
9.0
9.0
9.0
9.0
10.0
11.0
11.0
11.0
11.0
11.0
11.0
12.0
12.0
13.0
13.0
13.0
13.0
14.0
14.0
14.0
15.0
15.0
15.0
15.0
15.0
16.0
16.0
16.0
17.0
17.0
17.0
17.0
17.0
18.0
18.0
18.0
19.0
19.0
20.0
20.0
20.0
20.0
20.0
20.0
21.0
21.0
21.0
21.0
21.0
22.0
23.0
23.0
23.0
23.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
26.0
27.0
27.0
28.0
28.0
29.0
30.0
30.0
30.0
30.0
30.0
30.0
30.0
31.0
31.0
31.0
32.0
33.0
33.0
33.0
33.0
34.0
34.0
34.0
34.0
35.0
35.0
35.0
35.0
35.0
35.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
37.0
37.0
37.0
37.0
37.0
38.0
38.0
39.0
39.0
39.0
39.0
39.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
41.0
41.0
41.0
41.0
42.0
43.0
43.0
43.0
43.0
43.0
43.0
44.0
45.0
45.0
45.0
45.0
46.0
46.0
47.0
47.0
48.0

In [23]:
for i, j in df.iterrows():
    if i == j['Filament ID']:
        print('hi')

hi
hi
hi
hi
hi


In [26]:
for i, j in df.iterrows():
    print(j)

px            -2.81356
py            -2.00726
pz            -1.79707
px2           -3.34829
py2           -2.21085
pz2           -2.10106
Filament ID    0.00000
Name: 0, dtype: float64
px            -3.34829
py            -2.21085
pz            -2.10106
px2           -3.55129
py2           -2.20702
pz2           -2.52764
Filament ID    0.00000
Name: 1, dtype: float64
px            -3.55129
py            -2.20702
pz            -2.52764
px2           -3.54704
py2           -2.07235
pz2           -2.75681
Filament ID    0.00000
Name: 2, dtype: float64
px            -3.54704
py            -2.07235
pz            -2.75681
px2           -3.62038
py2           -2.03417
pz2           -2.75514
Filament ID    0.00000
Name: 3, dtype: float64
px            -3.62038
py            -2.03417
pz            -2.75514
px2           -3.93710
py2           -2.23730
pz2           -2.73826
Filament ID    0.00000
Name: 4, dtype: float64
px            -3.93710
py            -2.23730
pz            -2.73826
px2   

In [33]:
for i, j in df.iterrows():
    for k in j:
        if k == j['Filament ID']:
            print(j['Filament ID'])

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
3.0
3.0
3.0
3.0
3.0
4.0
4.0
4.0
4.0
5.0
6.0
6.0
6.0
6.0
6.0
7.0
7.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
9.0
9.0
9.0
9.0
10.0
11.0
11.0
11.0
11.0
11.0
11.0
12.0
12.0
13.0
13.0
13.0
13.0
14.0
14.0
14.0
15.0
15.0
15.0
15.0
15.0
16.0
16.0
16.0
17.0
17.0
17.0
17.0
17.0
18.0
18.0
18.0
19.0
19.0
20.0
20.0
20.0
20.0
20.0
20.0
21.0
21.0
21.0
21.0
21.0
22.0
23.0
23.0
23.0
23.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
26.0
27.0
27.0
28.0
28.0
29.0
30.0
30.0
30.0
30.0
30.0
30.0
30.0
31.0
31.0
31.0
32.0
33.0
33.0
33.0
33.0
34.0
34.0
34.0
34.0
35.0
35.0
35.0
35.0
35.0
35.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
37.0
37.0
37.0
37.0
37.0
38.0
38.0
39.0
39.0
39.0
39.0
39.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
40.0
41.0
41.0
41.0
41.0
42.0
43.0
43.0
43.0
43.0
43.0
43.0
44.0
45.0
45.0
45.0
45.0
46.0
46.0
47.0
47.0
48.0

In [ ]:
for i, j in df.iterrows():
    while 

In [60]:
len(df.loc[df['Filament ID'] == 0])

9

In [65]:
for i in range(len(df)): #interesting 
    print(df.loc[df['Filament ID'] == i])

        px       py       pz      px2      py2      pz2  Filament ID
0 -2.81356 -2.00726 -1.79707 -3.34829 -2.21085 -2.10106            0
1 -3.34829 -2.21085 -2.10106 -3.55129 -2.20702 -2.52764            0
2 -3.55129 -2.20702 -2.52764 -3.54704 -2.07235 -2.75681            0
3 -3.54704 -2.07235 -2.75681 -3.62038 -2.03417 -2.75514            0
4 -3.62038 -2.03417 -2.75514 -3.93710 -2.23730 -2.73826            0
5 -3.93710 -2.23730 -2.73826 -4.38406 -2.60411 -2.52365            0
6 -4.38406 -2.60411 -2.52365 -4.64688 -2.84577 -2.42487            0
7 -4.64688 -2.84577 -2.42487 -4.78000 -2.92492 -2.53663            0
8 -4.78000 -2.92492 -2.53663 -4.79659 -2.93978 -2.53340            0
        px       py        pz      px2      py2       pz2  Filament ID
0 -2.81356 -2.00726 -1.797070 -2.42291 -1.79406 -1.743000            1
1 -2.42291 -1.79406 -1.743000 -2.60880 -2.04234 -0.950936            1
2 -2.60880 -2.04234 -0.950936 -2.54813 -2.10565 -0.169142            1
3 -2.54813 -2.10565 -0.169

In [66]:
for i in range(len(df)): #interesting 
    print(len(df.loc[df['Filament ID'] == i]))

9
6
7
5
4
1
5
2
11
4
1
6
2
4
3
5
3
5
3
2
6
5
1
4
12
8
1
2
2
1
7
3
1
4
4
6
9
5
2
5
14
4
1
6
1
4
2
2
3
2
2
3
2
3
6
7
11
4
1
1
3
1
2
1
3
6
2
1
11
3
1
1
1
7
3
1
5
1
3
1
1
3
1
1
1
5
1
6
2
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [183]:
for i in range(len(df)):
    fils = df.loc[df['Filament ID'] == i]
    N = len(fils)
    for j in fils:
        print(fils)

    

        px       py       pz      px2      py2      pz2  Filament ID
0 -2.81356 -2.00726 -1.79707 -3.34829 -2.21085 -2.10106            0
1 -3.34829 -2.21085 -2.10106 -3.55129 -2.20702 -2.52764            0
2 -3.55129 -2.20702 -2.52764 -3.54704 -2.07235 -2.75681            0
3 -3.54704 -2.07235 -2.75681 -3.62038 -2.03417 -2.75514            0
4 -3.62038 -2.03417 -2.75514 -3.93710 -2.23730 -2.73826            0
5 -3.93710 -2.23730 -2.73826 -4.38406 -2.60411 -2.52365            0
6 -4.38406 -2.60411 -2.52365 -4.64688 -2.84577 -2.42487            0
7 -4.64688 -2.84577 -2.42487 -4.78000 -2.92492 -2.53663            0
8 -4.78000 -2.92492 -2.53663 -4.79659 -2.93978 -2.53340            0
        px       py       pz      px2      py2      pz2  Filament ID
0 -2.81356 -2.00726 -1.79707 -3.34829 -2.21085 -2.10106            0
1 -3.34829 -2.21085 -2.10106 -3.55129 -2.20702 -2.52764            0
2 -3.55129 -2.20702 -2.52764 -3.54704 -2.07235 -2.75681            0
3 -3.54704 -2.07235 -2.75681 -3.62

In [131]:
for i in range(len(df)):
    fils = df.loc[df['Filament ID'] == i]
    N = len(fils)
    for j in range(N):
        #N = len(fils[j])
        AG = np.zeros((N,3))
        #AG[i] = gal1 - df.iloc[0:,-4] #doesnt work 


In [153]:
for i in range(len(df)):
    fils = df.loc[df['Filament ID'] == i]
    print(fils)

        px       py        pz      px2      py2       pz2  Filament ID
0 -2.81356 -2.00726 -1.797070 -2.42291 -1.79406 -1.743000            1
1 -2.42291 -1.79406 -1.743000 -2.60880 -2.04234 -0.950936            1
2 -2.60880 -2.04234 -0.950936 -2.54813 -2.10565 -0.169142            1
3 -2.54813 -2.10565 -0.169142 -2.14741 -1.74321 -0.041595            1
4 -2.14741 -1.74321 -0.041595 -1.84651 -1.46575  0.088692            1
5 -1.84651 -1.46575  0.088692 -1.82022 -1.45434  0.119345            1
         px       py       pz       px2      py2      pz2  Filament ID
0  0.072087 -5.67172  2.83266  0.823442 -5.41287  3.59610            2
1  0.823442 -5.41287  3.59610  0.486821 -5.25539  4.66427            2
2  0.486821 -5.25539  4.66427  0.720634 -5.33619  4.65914            2
3  0.720634 -5.33619  4.65914  1.157150 -5.39709  4.85646            2
4  1.157150 -5.39709  4.85646  1.862230 -5.60071  5.30492            2
5  1.862230 -5.60071  5.30492  2.304810 -5.72357  5.59572            2
6  2.3

In [176]:
for i in range(len(df)):
    print(df.iloc[i,0],df.iloc[i,1],df.iloc[i,2]) #ONTO SOMETHING HERE

-2.81356 -2.00726 -1.79707
-3.34829 -2.21085 -2.10106
-3.55129 -2.20702 -2.52764
-3.54704 -2.07235 -2.75681
-3.62038 -2.03417 -2.75514
-3.9371 -2.2373 -2.73826
-4.38406 -2.60411 -2.52365
-4.64688 -2.84577 -2.42487
-4.78 -2.92492 -2.53663
-2.81356 -2.00726 -1.79707
-2.42291 -1.79406 -1.743
-2.6088 -2.04234 -0.950936
-2.54813 -2.10565 -0.169142
-2.14741 -1.74321 -0.0415953
-1.84651 -1.46575 0.0886922
0.0720867 -5.67172 2.83266
0.823442 -5.41287 3.5961
0.486821 -5.25539 4.66427
0.720634 -5.33619 4.65914
1.15715 -5.39709 4.85646
1.86223 -5.60071 5.30492
2.30481 -5.72357 5.59572
0.0720867 -5.67172 2.83266
-1.96428 -5.30094 3.07536
-3.00944 -4.59725 3.04495
-2.86515 -4.30749 2.70464
-2.83073 -4.10602 2.41469
2.36955 -5.65897 5.56633
2.62239 -5.72224 5.48646
3.02267 -5.80552 5.3958
3.23457 -5.84893 5.31946
-2.87523 -3.97738 2.37498
-1.06399 -1.10514 1.41526
-0.43938 -0.723715 1.19085
-0.238136 -0.39628 0.80612
-0.144078 -0.108052 0.76654
-0.0705347 0.0216042 0.758018
-1.06399 -1.10514 1.41526

In [207]:
for i, j in df.iterrows():
    for k in range(len(j)):
        if j['Filament ID']==k:
            print(df.iloc[k,0],df.iloc[k,1],df.iloc[k,2])

-2.81356 -2.00726 -1.79707
-2.81356 -2.00726 -1.79707
-2.81356 -2.00726 -1.79707
-2.81356 -2.00726 -1.79707
-2.81356 -2.00726 -1.79707
-2.81356 -2.00726 -1.79707
-2.81356 -2.00726 -1.79707
-2.81356 -2.00726 -1.79707
-2.81356 -2.00726 -1.79707
-3.34829 -2.21085 -2.10106
-3.34829 -2.21085 -2.10106
-3.34829 -2.21085 -2.10106
-3.34829 -2.21085 -2.10106
-3.34829 -2.21085 -2.10106
-3.34829 -2.21085 -2.10106
-3.55129 -2.20702 -2.52764
-3.55129 -2.20702 -2.52764
-3.55129 -2.20702 -2.52764
-3.55129 -2.20702 -2.52764
-3.55129 -2.20702 -2.52764
-3.55129 -2.20702 -2.52764
-3.55129 -2.20702 -2.52764
-3.54704 -2.07235 -2.75681
-3.54704 -2.07235 -2.75681
-3.54704 -2.07235 -2.75681
-3.54704 -2.07235 -2.75681
-3.54704 -2.07235 -2.75681
-3.62038 -2.03417 -2.75514
-3.62038 -2.03417 -2.75514
-3.62038 -2.03417 -2.75514
-3.62038 -2.03417 -2.75514
-3.9371 -2.2373 -2.73826
-4.38406 -2.60411 -2.52365
-4.38406 -2.60411 -2.52365
-4.38406 -2.60411 -2.52365
-4.38406 -2.60411 -2.52365
-4.38406 -2.60411 -2.52365


In [211]:
for i, j in df.iterrows():
    for k in range(len(j)):
        if j['Filament ID']==k:
            print(j['px'])

-2.81356
-3.34829
-3.55129
-3.54704
-3.62038
-3.9371
-4.38406
-4.64688
-4.78
-2.81356
-2.42291
-2.6088
-2.54813
-2.14741
-1.84651
0.0720867
0.823442
0.486821
0.720634
1.15715
1.86223
2.30481
0.0720867
-1.96428
-3.00944
-2.86515
-2.83073
2.36955
2.62239
3.02267
3.23457
-2.87523
-1.06399
-0.43938
-0.238136
-0.144078
-0.0705347


In [57]:
for i, j in df.iterrows():
    for k in j:
        while k == j['Filament ID']:
            k += 1
            l.append(k)
            #print(j['Filament ID'])
            
            

In [192]:
df

px       py       pz       px2      py2      pz2  Filament ID
0  -2.813560 -2.00726 -1.79707 -3.348290 -2.21085 -2.10106            0
1  -3.348290 -2.21085 -2.10106 -3.551290 -2.20702 -2.52764            0
2  -3.551290 -2.20702 -2.52764 -3.547040 -2.07235 -2.75681            0
3  -3.547040 -2.07235 -2.75681 -3.620380 -2.03417 -2.75514            0
4  -3.620380 -2.03417 -2.75514 -3.937100 -2.23730 -2.73826            0
..       ...      ...      ...       ...      ...      ...          ...
5  -2.991490 -4.04842  2.25934 -2.875230 -3.97738  2.37498           87
0   6.295170 -4.11047  3.60174  6.229390 -4.13554  3.36975           88
1   6.229390 -4.13554  3.36975  6.179120 -4.20421  3.14064           88
0   0.287103  6.25466  1.18162  0.284161  6.26514  1.18052           89
1   0.284161  6.26514  1.18052  0.281220  6.27562  1.17942           89

[335 rows x 7 columns]

In [41]:
df.iloc[0,:-4] #this gives px,py,pz for the first row 

px   -2.81356
py   -2.00726
pz   -1.79707
Name: 0, dtype: float64

In [43]:
gal1 - df.iloc[0,:-4] #it works!!!!!

px   -1.406780
py   -1.003630
pz   -0.898535
Name: 0, dtype: float64

In [44]:
for i, j in df.iterrows():
    for k in j:
        if k == j['Filament ID']:
            N = len()

TypeError: object of type 'float' has no len()

In [212]:
df

px       py       pz       px2      py2      pz2  Filament ID
0  -2.813560 -2.00726 -1.79707 -3.348290 -2.21085 -2.10106            0
1  -3.348290 -2.21085 -2.10106 -3.551290 -2.20702 -2.52764            0
2  -3.551290 -2.20702 -2.52764 -3.547040 -2.07235 -2.75681            0
3  -3.547040 -2.07235 -2.75681 -3.620380 -2.03417 -2.75514            0
4  -3.620380 -2.03417 -2.75514 -3.937100 -2.23730 -2.73826            0
..       ...      ...      ...       ...      ...      ...          ...
5  -2.991490 -4.04842  2.25934 -2.875230 -3.97738  2.37498           87
0   6.295170 -4.11047  3.60174  6.229390 -4.13554  3.36975           88
1   6.229390 -4.13554  3.36975  6.179120 -4.20421  3.14064           88
0   0.287103  6.25466  1.18162  0.284161  6.26514  1.18052           89
1   0.284161  6.26514  1.18052  0.281220  6.27562  1.17942           89

[335 rows x 7 columns]

In [217]:
dfarray = np.array(df)
dfarray[0][-1]

0.0

In [219]:
for i in range(len(dfarray)):
    if dfarray[i][-1] == 0:
        print(dfarray[i][:3])

[-2.81356 -2.00726 -1.79707]
[-3.34829 -2.21085 -2.10106]
[-3.55129 -2.20702 -2.52764]
[-3.54704 -2.07235 -2.75681]
[-3.62038 -2.03417 -2.75514]
[-3.9371  -2.2373  -2.73826]
[-4.38406 -2.60411 -2.52365]
[-4.64688 -2.84577 -2.42487]
[-4.78    -2.92492 -2.53663]


In [259]:
for i in range(len(dfarray)):
    if dfarray[i][-1] == 0:
        print(dfarray[i][:3])
    if dfarray[i][-1] == 1:
        print(dfarray[i][:3])

[-2.81356 -2.00726 -1.79707]
[-3.34829 -2.21085 -2.10106]
[-3.55129 -2.20702 -2.52764]
[-3.54704 -2.07235 -2.75681]
[-3.62038 -2.03417 -2.75514]
[-3.9371  -2.2373  -2.73826]
[-4.38406 -2.60411 -2.52365]
[-4.64688 -2.84577 -2.42487]
[-4.78    -2.92492 -2.53663]
[-2.81356 -2.00726 -1.79707]
[-2.42291 -1.79406 -1.743  ]
[-2.6088   -2.04234  -0.950936]
[-2.54813  -2.10565  -0.169142]
[-2.14741   -1.74321   -0.0415953]
[-1.84651   -1.46575    0.0886922]


In [274]:
df[df['Filament ID']==0]

px       py       pz      px2      py2      pz2  Filament ID
0 -2.81356 -2.00726 -1.79707 -3.34829 -2.21085 -2.10106            0
1 -3.34829 -2.21085 -2.10106 -3.55129 -2.20702 -2.52764            0
2 -3.55129 -2.20702 -2.52764 -3.54704 -2.07235 -2.75681            0
3 -3.54704 -2.07235 -2.75681 -3.62038 -2.03417 -2.75514            0
4 -3.62038 -2.03417 -2.75514 -3.93710 -2.23730 -2.73826            0
5 -3.93710 -2.23730 -2.73826 -4.38406 -2.60411 -2.52365            0
6 -4.38406 -2.60411 -2.52365 -4.64688 -2.84577 -2.42487            0
7 -4.64688 -2.84577 -2.42487 -4.78000 -2.92492 -2.53663            0
8 -4.78000 -2.92492 -2.53663 -4.79659 -2.93978 -2.53340            0

In [267]:
for i in range(len(dfarray)):
    print(dfarray[i])

[-2.81356 -2.00726 -1.79707 -3.34829 -2.21085 -2.10106  0.     ]
[-3.34829 -2.21085 -2.10106 -3.55129 -2.20702 -2.52764  0.     ]
[-3.55129 -2.20702 -2.52764 -3.54704 -2.07235 -2.75681  0.     ]
[-3.54704 -2.07235 -2.75681 -3.62038 -2.03417 -2.75514  0.     ]
[-3.62038 -2.03417 -2.75514 -3.9371  -2.2373  -2.73826  0.     ]
[-3.9371  -2.2373  -2.73826 -4.38406 -2.60411 -2.52365  0.     ]
[-4.38406 -2.60411 -2.52365 -4.64688 -2.84577 -2.42487  0.     ]
[-4.64688 -2.84577 -2.42487 -4.78    -2.92492 -2.53663  0.     ]
[-4.78    -2.92492 -2.53663 -4.79659 -2.93978 -2.5334   0.     ]
[-2.81356 -2.00726 -1.79707 -2.42291 -1.79406 -1.743    1.     ]
[-2.42291  -1.79406  -1.743    -2.6088   -2.04234  -0.950936  1.      ]
[-2.6088   -2.04234  -0.950936 -2.54813  -2.10565  -0.169142  1.      ]
[-2.54813   -2.10565   -0.169142  -2.14741   -1.74321   -0.0415953
  1.       ]
[-2.14741   -1.74321   -0.0415953 -1.84651   -1.46575    0.0886922
  1.       ]
[-1.84651   -1.46575    0.0886922 -1.82022   -

In [291]:
dfarray[0][:-1]

array([-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106])

In [305]:
for i in range(len(dfarray)):
    for j in range(len(dfarray[i])):
        A = len(j)
        print(A)

TypeError: object of type 'int' has no len()

In [299]:
len(dfarray[0])

7

In [311]:
dfarray[0][:-3]

array([-2.81356, -2.00726, -1.79707, -3.34829])

In [313]:
for i in range(len(dfarray)):
    for j in range(len(dfarray[i])):
        print(dfarray[j][1])

-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726
-2.21085
-2.20702
-2.07235
-2.03417
-2.2373
-2.60411
-2.00726

In [314]:
dfarray[1]

array([-3.34829, -2.21085, -2.10106, -3.55129, -2.20702, -2.52764,
        0.     ])

In [316]:
dfarray[0]

array([-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106,
        0.     ])

In [318]:
for i in range(len(dfarray)):
    for j in range(len(dfarray[i])):
        A = np.zeros((len(dfarray[j][:-4])))
        print(A)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]

In [321]:
for i in range(len(dfarray)):
    for j in range(len(dfarray[i])):
        A = np.zeros((len(dfarray[j][:-4])))
        A[j] = dfarray[j][:-4]
        print(A)

ValueError: setting an array element with a sequence.

In [326]:
dfarray[0][:-4]

array([-2.81356, -2.00726, -1.79707])

In [327]:
dfarray[0][-1]

0.0

In [328]:
dfarray[0][3:-1]

array([-3.34829, -2.21085, -2.10106])

In [329]:
dfarray[0]

array([-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106,
        0.     ])

In [344]:
for i in range(len(dfarray)):
    if dfarray[i][-1] == 0:
        print('hi')
    if dfarray[i][-1] == i+1:
        print('HI')

hi
hi
hi
hi
hi
hi
hi
hi
hi


In [349]:
ids = np.zeros(len(dfarray))
for i in range(len(dfarray)):
    ids[i]= dfarray[i][-1]
ids

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,
        3.,  4.,  4.,  4.,  4.,  5.,  6.,  6.,  6.,  6.,  6.,  7.,  7.,
        8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  9.,  9.,
        9.,  9., 10., 11., 11., 11., 11., 11., 11., 12., 12., 13., 13.,
       13., 13., 14., 14., 14., 15., 15., 15., 15., 15., 16., 16., 16.,
       17., 17., 17., 17., 17., 18., 18., 18., 19., 19., 20., 20., 20.,
       20., 20., 20., 21., 21., 21., 21., 21., 22., 23., 23., 23., 23.,
       24., 24., 24., 24., 24., 24., 24., 24., 24., 24., 24., 24., 25.,
       25., 25., 25., 25., 25., 25., 25., 26., 27., 27., 28., 28., 29.,
       30., 30., 30., 30., 30., 30., 30., 31., 31., 31., 32., 33., 33.,
       33., 33., 34., 34., 34., 34., 35., 35., 35., 35., 35., 35., 36.,
       36., 36., 36., 36., 36., 36., 36., 36., 37., 37., 37., 37., 37.,
       38., 38., 39., 39., 39., 39., 39., 40., 40., 40., 40., 40

In [352]:
for i in range(len(dfarray)):
    if dfarray[i][-1] == ids[i]:
        print('hi')

hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
h

In [355]:
df

px       py       pz       px2      py2      pz2  Filament ID
0  -2.813560 -2.00726 -1.79707 -3.348290 -2.21085 -2.10106            0
1  -3.348290 -2.21085 -2.10106 -3.551290 -2.20702 -2.52764            0
2  -3.551290 -2.20702 -2.52764 -3.547040 -2.07235 -2.75681            0
3  -3.547040 -2.07235 -2.75681 -3.620380 -2.03417 -2.75514            0
4  -3.620380 -2.03417 -2.75514 -3.937100 -2.23730 -2.73826            0
..       ...      ...      ...       ...      ...      ...          ...
5  -2.991490 -4.04842  2.25934 -2.875230 -3.97738  2.37498           87
0   6.295170 -4.11047  3.60174  6.229390 -4.13554  3.36975           88
1   6.229390 -4.13554  3.36975  6.179120 -4.20421  3.14064           88
0   0.287103  6.25466  1.18162  0.284161  6.26514  1.18052           89
1   0.284161  6.26514  1.18052  0.281220  6.27562  1.17942           89

[335 rows x 7 columns]

In [356]:
np.where(df['Filament ID'] == 0)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)

In [435]:
slices = np.where(ids == 0) #numpy array version
dfarray[slices]

array([[-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106,
         0.     ],
       [-3.34829, -2.21085, -2.10106, -3.55129, -2.20702, -2.52764,
         0.     ],
       [-3.55129, -2.20702, -2.52764, -3.54704, -2.07235, -2.75681,
         0.     ],
       [-3.54704, -2.07235, -2.75681, -3.62038, -2.03417, -2.75514,
         0.     ],
       [-3.62038, -2.03417, -2.75514, -3.9371 , -2.2373 , -2.73826,
         0.     ],
       [-3.9371 , -2.2373 , -2.73826, -4.38406, -2.60411, -2.52365,
         0.     ],
       [-4.38406, -2.60411, -2.52365, -4.64688, -2.84577, -2.42487,
         0.     ],
       [-4.64688, -2.84577, -2.42487, -4.78   , -2.92492, -2.53663,
         0.     ],
       [-4.78   , -2.92492, -2.53663, -4.79659, -2.93978, -2.5334 ,
         0.     ]])

In [451]:
slices = []
for i in range(len(dfarray)):
    S = np.where(ids == i)
    slices.append(S)
slices

[(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),),
 (array([ 9, 10, 11, 12, 13, 14]),),
 (array([15, 16, 17, 18, 19, 20, 21]),),
 (array([22, 23, 24, 25, 26]),),
 (array([27, 28, 29, 30]),),
 (array([31]),),
 (array([32, 33, 34, 35, 36]),),
 (array([37, 38]),),
 (array([39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),),
 (array([50, 51, 52, 53]),),
 (array([54]),),
 (array([55, 56, 57, 58, 59, 60]),),
 (array([61, 62]),),
 (array([63, 64, 65, 66]),),
 (array([67, 68, 69]),),
 (array([70, 71, 72, 73, 74]),),
 (array([75, 76, 77]),),
 (array([78, 79, 80, 81, 82]),),
 (array([83, 84, 85]),),
 (array([86, 87]),),
 (array([88, 89, 90, 91, 92, 93]),),
 (array([94, 95, 96, 97, 98]),),
 (array([99]),),
 (array([100, 101, 102, 103]),),
 (array([104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]),),
 (array([116, 117, 118, 119, 120, 121, 122, 123]),),
 (array([124]),),
 (array([125, 126]),),
 (array([127, 128]),),
 (array([129]),),
 (array([130, 131, 132, 133, 134, 135, 136]),),
 (array([137, 138, 13

In [453]:
len(slices)

335

In [454]:
len(ids)

335

In [459]:
len(slices[1][0])

6

In [461]:
slices2 = []
for i in range(len(slices)):
    check = len(slices[i][0]) #checks length of the smaller arrays
    if check != 0:
        slices2.append(slices[i])
slices2

[(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),),
 (array([ 9, 10, 11, 12, 13, 14]),),
 (array([15, 16, 17, 18, 19, 20, 21]),),
 (array([22, 23, 24, 25, 26]),),
 (array([27, 28, 29, 30]),),
 (array([31]),),
 (array([32, 33, 34, 35, 36]),),
 (array([37, 38]),),
 (array([39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),),
 (array([50, 51, 52, 53]),),
 (array([54]),),
 (array([55, 56, 57, 58, 59, 60]),),
 (array([61, 62]),),
 (array([63, 64, 65, 66]),),
 (array([67, 68, 69]),),
 (array([70, 71, 72, 73, 74]),),
 (array([75, 76, 77]),),
 (array([78, 79, 80, 81, 82]),),
 (array([83, 84, 85]),),
 (array([86, 87]),),
 (array([88, 89, 90, 91, 92, 93]),),
 (array([94, 95, 96, 97, 98]),),
 (array([99]),),
 (array([100, 101, 102, 103]),),
 (array([104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]),),
 (array([116, 117, 118, 119, 120, 121, 122, 123]),),
 (array([124]),),
 (array([125, 126]),),
 (array([127, 128]),),
 (array([129]),),
 (array([130, 131, 132, 133, 134, 135, 136]),),
 (array([137, 138, 13

In [464]:
len(slices2) #correct -- should correspond with number of unique filament IDs that there are 

90

In [431]:
df

px       py       pz       px2      py2      pz2  Filament ID
0  -2.813560 -2.00726 -1.79707 -3.348290 -2.21085 -2.10106            0
1  -3.348290 -2.21085 -2.10106 -3.551290 -2.20702 -2.52764            0
2  -3.551290 -2.20702 -2.52764 -3.547040 -2.07235 -2.75681            0
3  -3.547040 -2.07235 -2.75681 -3.620380 -2.03417 -2.75514            0
4  -3.620380 -2.03417 -2.75514 -3.937100 -2.23730 -2.73826            0
..       ...      ...      ...       ...      ...      ...          ...
5  -2.991490 -4.04842  2.25934 -2.875230 -3.97738  2.37498           87
0   6.295170 -4.11047  3.60174  6.229390 -4.13554  3.36975           88
1   6.229390 -4.13554  3.36975  6.179120 -4.20421  3.14064           88
0   0.287103  6.25466  1.18162  0.284161  6.26514  1.18052           89
1   0.284161  6.26514  1.18052  0.281220  6.27562  1.17942           89

[335 rows x 7 columns]

In [437]:
dfarray[31] # for some reason there is a filament with only one fil ID == 5???? 

array([-2.87523, -3.97738,  2.37498, -2.87142, -3.9203 ,  2.37128,
        5.     ])

In [467]:
dfarray[0]

array([-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106,
        0.     ])

In [465]:
slices2[0]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)

In [474]:
dfarray[slices2[0]]

array([[-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106,
         0.     ],
       [-3.34829, -2.21085, -2.10106, -3.55129, -2.20702, -2.52764,
         0.     ],
       [-3.55129, -2.20702, -2.52764, -3.54704, -2.07235, -2.75681,
         0.     ],
       [-3.54704, -2.07235, -2.75681, -3.62038, -2.03417, -2.75514,
         0.     ],
       [-3.62038, -2.03417, -2.75514, -3.9371 , -2.2373 , -2.73826,
         0.     ],
       [-3.9371 , -2.2373 , -2.73826, -4.38406, -2.60411, -2.52365,
         0.     ],
       [-4.38406, -2.60411, -2.52365, -4.64688, -2.84577, -2.42487,
         0.     ],
       [-4.64688, -2.84577, -2.42487, -4.78   , -2.92492, -2.53663,
         0.     ],
       [-4.78   , -2.92492, -2.53663, -4.79659, -2.93978, -2.5334 ,
         0.     ]])

In [477]:
dfarray[slices2[0]]

array([[-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106,
         0.     ],
       [-3.34829, -2.21085, -2.10106, -3.55129, -2.20702, -2.52764,
         0.     ],
       [-3.55129, -2.20702, -2.52764, -3.54704, -2.07235, -2.75681,
         0.     ],
       [-3.54704, -2.07235, -2.75681, -3.62038, -2.03417, -2.75514,
         0.     ],
       [-3.62038, -2.03417, -2.75514, -3.9371 , -2.2373 , -2.73826,
         0.     ],
       [-3.9371 , -2.2373 , -2.73826, -4.38406, -2.60411, -2.52365,
         0.     ],
       [-4.38406, -2.60411, -2.52365, -4.64688, -2.84577, -2.42487,
         0.     ],
       [-4.64688, -2.84577, -2.42487, -4.78   , -2.92492, -2.53663,
         0.     ],
       [-4.78   , -2.92492, -2.53663, -4.79659, -2.93978, -2.5334 ,
         0.     ]])

In [485]:
for i in range(len(slices2)):
    fil = dfarray[slices2[i]] #this will do one slice of the first filament and iterate 
    for j in fil:
        A = j[:-4]
        print(A)

[-2.81356 -2.00726 -1.79707]
[-3.34829 -2.21085 -2.10106]
[-3.55129 -2.20702 -2.52764]
[-3.54704 -2.07235 -2.75681]
[-3.62038 -2.03417 -2.75514]
[-3.9371  -2.2373  -2.73826]
[-4.38406 -2.60411 -2.52365]
[-4.64688 -2.84577 -2.42487]
[-4.78    -2.92492 -2.53663]
[-2.81356 -2.00726 -1.79707]
[-2.42291 -1.79406 -1.743  ]
[-2.6088   -2.04234  -0.950936]
[-2.54813  -2.10565  -0.169142]
[-2.14741   -1.74321   -0.0415953]
[-1.84651   -1.46575    0.0886922]
[ 0.0720867 -5.67172    2.83266  ]
[ 0.823442 -5.41287   3.5961  ]
[ 0.486821 -5.25539   4.66427 ]
[ 0.720634 -5.33619   4.65914 ]
[ 1.15715 -5.39709  4.85646]
[ 1.86223 -5.60071  5.30492]
[ 2.30481 -5.72357  5.59572]
[ 0.0720867 -5.67172    2.83266  ]
[-1.96428 -5.30094  3.07536]
[-3.00944 -4.59725  3.04495]
[-2.86515 -4.30749  2.70464]
[-2.83073 -4.10602  2.41469]
[ 2.36955 -5.65897  5.56633]
[ 2.62239 -5.72224  5.48646]
[ 3.02267 -5.80552  5.3958 ]
[ 3.23457 -5.84893  5.31946]
[-2.87523 -3.97738  2.37498]
[-1.06399 -1.10514  1.41526]
[-0.

In [505]:
for i in range(len(slices2)):
    fil = dfarray[slices2[i]] #this will do one slice of the first filament and iterate 
    for j in range(len(fil)): #this is iterating over the individual filament points
        A = fil[i][:-4] ; B = fil[i][3:-1] ; AB = [B-A] ; AG = gal1 - A
        u = AB / np.linalg.norm(AB)



IndexError: index 4 is out of bounds for axis 0 with size 4

In [513]:
dfarray

array([[-2.81356 , -2.00726 , -1.79707 , ..., -2.21085 , -2.10106 ,
         0.      ],
       [-3.34829 , -2.21085 , -2.10106 , ..., -2.20702 , -2.52764 ,
         0.      ],
       [-3.55129 , -2.20702 , -2.52764 , ..., -2.07235 , -2.75681 ,
         0.      ],
       ...,
       [ 6.22939 , -4.13554 ,  3.36975 , ..., -4.20421 ,  3.14064 ,
        88.      ],
       [ 0.287103,  6.25466 ,  1.18162 , ...,  6.26514 ,  1.18052 ,
        89.      ],
       [ 0.284161,  6.26514 ,  1.18052 , ...,  6.27562 ,  1.17942 ,
        89.      ]])

In [520]:
filpoints = []
for i in range(len(slices2)):
    fil = dfarray[slices2[i]] #this will do one slice of the first filament and iterate 
    filpoints.append(fil)
type(filpoints)

list

In [521]:
filpoints

[array([[-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106,
          0.     ],
        [-3.34829, -2.21085, -2.10106, -3.55129, -2.20702, -2.52764,
          0.     ],
        [-3.55129, -2.20702, -2.52764, -3.54704, -2.07235, -2.75681,
          0.     ],
        [-3.54704, -2.07235, -2.75681, -3.62038, -2.03417, -2.75514,
          0.     ],
        [-3.62038, -2.03417, -2.75514, -3.9371 , -2.2373 , -2.73826,
          0.     ],
        [-3.9371 , -2.2373 , -2.73826, -4.38406, -2.60411, -2.52365,
          0.     ],
        [-4.38406, -2.60411, -2.52365, -4.64688, -2.84577, -2.42487,
          0.     ],
        [-4.64688, -2.84577, -2.42487, -4.78   , -2.92492, -2.53663,
          0.     ],
        [-4.78   , -2.92492, -2.53663, -4.79659, -2.93978, -2.5334 ,
          0.     ]]),
 array([[-2.81356  , -2.00726  , -1.79707  , -2.42291  , -1.79406  ,
         -1.743    ,  1.       ],
        [-2.42291  , -1.79406  , -1.743    , -2.6088   , -2.04234  ,
         -0.950936 ,  1. 

In [522]:
for i in range(len(filpoints)):
    A = filpoints[i][:-4]
    print(A)

[[-2.81356 -2.00726 -1.79707 -3.34829 -2.21085 -2.10106  0.     ]
 [-3.34829 -2.21085 -2.10106 -3.55129 -2.20702 -2.52764  0.     ]
 [-3.55129 -2.20702 -2.52764 -3.54704 -2.07235 -2.75681  0.     ]
 [-3.54704 -2.07235 -2.75681 -3.62038 -2.03417 -2.75514  0.     ]
 [-3.62038 -2.03417 -2.75514 -3.9371  -2.2373  -2.73826  0.     ]]
[[-2.81356  -2.00726  -1.79707  -2.42291  -1.79406  -1.743     1.      ]
 [-2.42291  -1.79406  -1.743    -2.6088   -2.04234  -0.950936  1.      ]]
[[ 0.0720867 -5.67172    2.83266    0.823442  -5.41287    3.5961
   2.       ]
 [ 0.823442  -5.41287    3.5961     0.486821  -5.25539    4.66427
   2.       ]
 [ 0.486821  -5.25539    4.66427    0.720634  -5.33619    4.65914
   2.       ]]
[[ 0.0720867 -5.67172    2.83266   -1.96428   -5.30094    3.07536
   3.       ]]
[]
[]
[[-1.06399  -1.10514   1.41526  -0.43938  -0.723715  1.19085   6.      ]]
[]
[[-5.06605e-02  1.35131e-01  7.72572e-01  1.12098e-02  1.80649e-02
   7.35022e-01  8.00000e+00]
 [ 1.12098e-02  1.8064

#### OK let's try this again 
- segments 1 and 2 (the As and Bs) are ***already*** created in the dataframe 
- therefore there is no need to separate filament by ID (at least not yet -- later we might to optimize code)

In [524]:
df

px       py       pz       px2      py2      pz2  Filament ID
0  -2.813560 -2.00726 -1.79707 -3.348290 -2.21085 -2.10106            0
1  -3.348290 -2.21085 -2.10106 -3.551290 -2.20702 -2.52764            0
2  -3.551290 -2.20702 -2.52764 -3.547040 -2.07235 -2.75681            0
3  -3.547040 -2.07235 -2.75681 -3.620380 -2.03417 -2.75514            0
4  -3.620380 -2.03417 -2.75514 -3.937100 -2.23730 -2.73826            0
..       ...      ...      ...       ...      ...      ...          ...
5  -2.991490 -4.04842  2.25934 -2.875230 -3.97738  2.37498           87
0   6.295170 -4.11047  3.60174  6.229390 -4.13554  3.36975           88
1   6.229390 -4.13554  3.36975  6.179120 -4.20421  3.14064           88
0   0.287103  6.25466  1.18162  0.284161  6.26514  1.18052           89
1   0.284161  6.26514  1.18052  0.281220  6.27562  1.17942           89

[335 rows x 7 columns]

In [527]:
dfarray2 = np.array(df)
dfarray2[0] #same thing as dfarray

array([-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106,
        0.     ])

In [528]:
dfarray[0]

array([-2.81356, -2.00726, -1.79707, -3.34829, -2.21085, -2.10106,
        0.     ])

In [531]:
exampleA = dfarray[0][:-4]
exampleA

array([-2.81356, -2.00726, -1.79707])

In [532]:
exampleA.shape

(3,)

In [535]:
exampleB = dfarray[0][3:-1]
exampleB

array([-3.34829, -2.21085, -2.10106])

In [529]:
len(dfarray)

335

In [538]:
#TEST1 - to see if slicing works
A = np.zeros(3) ; B = np.zeros(3) ; AB = np.zeros(3) ; AG = np.zeros(3) ; u = np.zeros(3) #dont need to create separate numpy arrays to fill (I think)
for i in range(len(dfarray)):
    A = dfarray[i][:-4] ; B = dfarray[i][3:-1] ; AB = B - A ; AG = gal1 - A
    print(A)


[-2.81356 -2.00726 -1.79707]
[-3.34829 -2.21085 -2.10106]
[-3.55129 -2.20702 -2.52764]
[-3.54704 -2.07235 -2.75681]
[-3.62038 -2.03417 -2.75514]
[-3.9371  -2.2373  -2.73826]
[-4.38406 -2.60411 -2.52365]
[-4.64688 -2.84577 -2.42487]
[-4.78    -2.92492 -2.53663]
[-2.81356 -2.00726 -1.79707]
[-2.42291 -1.79406 -1.743  ]
[-2.6088   -2.04234  -0.950936]
[-2.54813  -2.10565  -0.169142]
[-2.14741   -1.74321   -0.0415953]
[-1.84651   -1.46575    0.0886922]
[ 0.0720867 -5.67172    2.83266  ]
[ 0.823442 -5.41287   3.5961  ]
[ 0.486821 -5.25539   4.66427 ]
[ 0.720634 -5.33619   4.65914 ]
[ 1.15715 -5.39709  4.85646]
[ 1.86223 -5.60071  5.30492]
[ 2.30481 -5.72357  5.59572]
[ 0.0720867 -5.67172    2.83266  ]
[-1.96428 -5.30094  3.07536]
[-3.00944 -4.59725  3.04495]
[-2.86515 -4.30749  2.70464]
[-2.83073 -4.10602  2.41469]
[ 2.36955 -5.65897  5.56633]
[ 2.62239 -5.72224  5.48646]
[ 3.02267 -5.80552  5.3958 ]
[ 3.23457 -5.84893  5.31946]
[-2.87523 -3.97738  2.37498]
[-1.06399 -1.10514  1.41526]
[-0.

In [539]:
#TEST2 -- unit vector calculation 
for i in range(len(dfarray)):
    A = dfarray[i][:-4] ; B = dfarray[i][3:-1] ; AB = B - A ; AG = gal1 - A
    # get norm -- in old code had to check if AB == 0 
    u = A / np.linalg.norm(A)
    print(u)


[-0.7222649  -0.5152808  -0.46132323]
[-0.73927275 -0.48813608 -0.46389542]
[-0.72685155 -0.45171639 -0.5173385 ]
[-0.71695966 -0.41888204 -0.55723126]
[-0.72646571 -0.4081767  -0.55284659]
[-0.74398437 -0.42277723 -0.51744244]
[-0.77055551 -0.45770617 -0.44356428]
[-0.77912646 -0.47714052 -0.40656965]
[-0.77707606 -0.47549902 -0.41237541]
[-0.7222649  -0.5152808  -0.46132323]
[-0.69575628 -0.51517742 -0.50051516]
[-0.75684921 -0.59251128 -0.27587978]
[-0.76985459 -0.63617018 -0.05110208]
[-0.77630229 -0.63018144 -0.01503696]
[-0.78268031 -0.62128755  0.03759397]
[ 0.01136986 -0.89457117  0.44678087]
[ 0.12570659 -0.82632829  0.54898033]
[ 0.0691159  -0.74612849  0.66220485]
[ 0.10120523 -0.74941003  0.65432569]
[ 0.15739127 -0.73409225  0.66055776]
[ 0.23465985 -0.70574621  0.66847367]
[ 0.27669867 -0.68713005  0.67178131]
[ 0.01136986 -0.89457117  0.44678087]
[-0.30522371 -0.82369753  0.47787118]
[-0.47905985 -0.73181652  0.48471254]
[-0.49080196 -0.73787569  0.4633065 ]
[-0.51086589

In [541]:
#TEST3 -- distances 
distances = np.zeros(len(dfarray))
for i in range(len(dfarray)):
    A = dfarray[i][:-4] ; B = dfarray[i][3:-1] ; AB = B - A ; AG = gal1 - A
    # get norm -- in old code had to check if AB == 0 
    u = A / np.linalg.norm(A)
    #if statements to check separate cases
    if np.dot(AG, u) < 0:
        distances[i] = np.linalg.norm(gal1 - A)
    elif np.dot(AG, u) > np.linalg.norm(AB):
        distances[i] = np.linalg.norm(gal1 - B)
    elif np.dot(AG, u) < np.linalg.norm(AB):
        distances[i] = np.linalg.norm((np.cross((A-B), (A-gal1)))) / (np.linalg.norm(gal1-B))
distances

array([ 1.32439381,  1.05926726,  1.15669195,  1.14781461,  0.82491565,
        0.61112828,  0.32027637,  0.53150581,  0.58811836,  2.37041898,
        2.56496008,  3.16208176,  3.59830778,  3.97175495,  4.01339849,
        7.48776717,  8.41396438,  9.02013885,  9.16037762,  9.57314133,
       10.37849824, 10.89413996,  7.48776717,  6.60591952,  6.07756436,
        5.71667364,  5.40790539, 10.89488632, 11.00547865, 11.21347339,
       11.30802463,  5.33425309,  5.52210462,  5.88484158,  5.91237787,
        6.08513174,  6.19228689,  5.52210462,  4.06225181,  6.26992241,
        6.23295942,  6.18957189,  6.11483581,  5.89788745,  5.45833405,
        5.29777417,  5.19682758,  5.21825168,  5.26619392,  5.27862784,
        5.22007652,  5.15486373,  5.12979552,  5.13660802,  4.01339849,
       11.14023437, 10.66716204, 10.46840421, 10.27346939, 10.16620949,
       10.09992382, 11.14023437, 11.59508483, 11.37500073, 11.40702374,
       11.53868541, 11.59617326, 11.37500073, 11.51196192, 11.60

In [544]:
#FINAL TEST with smallest distance 
distances = np.zeros(len(dfarray))
for i in range(len(dfarray)):
    A = dfarray[i][:-4] ; B = dfarray[i][3:-1] ; AB = B - A ; AG = gal1 - A
    # get norm -- in old code had to check if AB == 0 
    u = A / np.linalg.norm(A)
    #if statements to check separate cases
    if np.dot(AG, u) < 0:
        distances[i] = np.linalg.norm(gal1 - A)
    elif np.dot(AG, u) > np.linalg.norm(AB):
        distances[i] = np.linalg.norm(gal1 - B)
    elif np.dot(AG, u) < np.linalg.norm(AB):
        distances[i] = np.linalg.norm((np.cross((A-B), (A-gal1)))) / (np.linalg.norm(gal1-B))
shortest_distance = np.min(distances)
shortest_distance

0.2144694553822457

### Now do this for many galaxies

In [608]:
shortest_distances = np.zeros(len(gals))
for h in range(len(gals)):
    distances = np.zeros(len(dfarray))
    for i in range(len(dfarray)):
        A = dfarray[i][:-4] ; B = dfarray[i][3:-1] ; AB = B - A ; AG = gals[h] - A
        # get norm -- in old code had to check if AB == 0 
        if np.any(AG > 9) or np.any(AG < -9):
            distances[i] = 100
            continue
        u = A / np.linalg.norm(A)
        #if statements to check separate cases
        if np.dot(AG, u) < 0:
            distances[i] = np.linalg.norm(gals[h] - A)
        elif np.dot(AG, u) > np.linalg.norm(AB):
            distances[i] = np.linalg.norm(gals[h] - B)
        elif np.dot(AG, u) < np.linalg.norm(AB):
            distances[i] = np.linalg.norm((np.cross((A-B), (A-gals[h])))) / (np.linalg.norm(gals[h]-B))
    shortest_distances[h] = np.min(distances)
shortest_distances


array([0.21446946, 0.09238936, 0.08740858, 0.29186156, 0.65343441,
       0.65343441, 4.95369007, 0.18457534, 4.58631185, 0.2554643 ,
       0.13209505, 0.14276085, 0.61212675, 0.07205791, 0.53272587,
       0.06064055, 0.33971993, 0.0676657 , 0.51034178, 0.30798705,
       5.39014425, 0.65421272])

In [609]:
#TEST FOR AG 
shortest_distances = np.zeros(len(gals))
for h in range(len(gals)):
    distances = np.zeros(len(dfarray))
    for i in range(len(dfarray)):
        A = dfarray[i][:-4] ; B = dfarray[i][3:-1] ; AB = B - A ; AG = gals[h] - A
        # get norm -- in old code had to check if AB == 0 
        print(AG)

[-1.40678  -1.00363  -0.898535]
[-0.87205  -0.80004  -0.594545]
[-0.66905  -0.80387  -0.167965]
[-0.6733   -0.93854   0.061205]
[-0.59996  -0.97672   0.059535]
[-0.28324  -0.77359   0.042655]
[ 0.16372  -0.40678  -0.171955]
[ 0.42654  -0.16512  -0.270735]
[ 0.55966  -0.08597  -0.158975]
[-1.40678  -1.00363  -0.898535]
[-1.79743  -1.21683  -0.952605]
[-1.61154  -0.96855  -1.744669]
[-1.67221  -0.90524  -2.526463]
[-2.07293   -1.26768   -2.6540097]
[-2.37383   -1.54514   -2.7842972]
[-4.2924267  2.66083   -5.528265 ]
[-5.043782  2.40198  -6.291705]
[-4.707161  2.2445   -7.359875]
[-4.940974  2.3253   -7.354745]
[-5.37749   2.3862   -7.552065]
[-6.08257   2.58982  -8.000525]
[-6.52515   2.71268  -8.291325]
[-4.2924267  2.66083   -5.528265 ]
[-2.25606   2.29005  -5.770965]
[-1.2109    1.58636  -5.740555]
[-1.35519   1.2966   -5.400245]
[-1.38961   1.09513  -5.110295]
[-6.58989   2.64808  -8.261935]
[-6.84273   2.71135  -8.182065]
[-7.24301   2.79463  -8.091405]
[-7.45491   2.83804  -8.0150

In [ ]:
shortest_distances = np.zeros(len(gals))
for h in range(len(gals)):
    distances = np.zeros(len(dfarray))
    for i in range(len(dfarray)):
        A = dfarray[i][:-4] ; B = dfarray[i][3:-1] ; AB = B - A ; AG = gals[h] - A
        # get norm -- in old code had to check if AB == 0 
        if 
        u = A / np.linalg.norm(A)
        #if statements to check separate cases
        if np.dot(AG, u) < 0:
            distances[i] = np.linalg.norm(gals[h] - A)
        elif np.dot(AG, u) > np.linalg.norm(AB):
            distances[i] = np.linalg.norm(gals[h] - B)
        elif np.dot(AG, u) < np.linalg.norm(AB):
            distances[i] = np.linalg.norm((np.cross((A-B), (A-gals[h])))) / (np.linalg.norm(gals[h]-B))
    shortest_distances[h] = np.min(distances)
shortest_distances

In [565]:
gal1

array([-4.22034 , -3.01089 , -2.695605])

In [600]:
def galfildist3(galaxies, filament_points):
     '''Finds the closest distances between an array of galaxies
        and array of filament points. "filpoints" array must be a
         simple 3d array of all coordinate points of a filament
          (in other words - not an array of arrays, which separates half filaments) 
          MUST GIVE A SPECIFIC TYPE OF ARRAY WHERE EVERY ELEMENT IS AN ARRAY OF SEGMENTS OF FILAMENT'''
     shortest_distances = np.zeros(len(galaxies))
     for h in range(len(galaxies)):
            distances = np.zeros(len(filament_points))
            for i in range(len(filament_points)):
                  A = filament_points[i][:-4] ; B = filament_points[i][3:-1] ; AB = B - A ; AG = galaxies[h] - A
                  #OPTIMIZATION: quickly skip iteration if any value for AG is really big 
                  if np.any(AG > 30) or np.any(AG < -30):
                        distances[i] = 100000.00
                        continue
                  else:
                  #get norm -- in old code had to check if AB == 0 
                        u = A / np.linalg.norm(A)
                        #if statements to check separate cases
                        if np.dot(AG, u) < 0:
                              distances[i] = np.linalg.norm(galaxies[h] - A)
                        elif np.dot(AG, u) > np.linalg.norm(AB):
                              distances[i] = np.linalg.norm(galaxies[h] - B)
                        elif np.dot(AG, u) < np.linalg.norm(AB):
                              distances[i] = np.linalg.norm((np.cross((A-B), (A-galaxies[h])))) / (np.linalg.norm(galaxies[h]-B))
                  shortest_distances[h] = np.min(distances)
     return shortest_distances

In [ ]:
def galfildist3(galaxies, filament_points): ##USE THIS ONE W OPTIMIZATION 
     '''Finds the closest distances between an array of galaxies
        and array of filament points. "filpoints" array must be a
         simple 3d array of all coordinate points of a filament
          (in other words - not an array of arrays, which separates half filaments) 
          MUST GIVE A SPECIFIC TYPE OF ARRAY WHERE EVERY ELEMENT IS AN ARRAY OF SEGMENTS OF FILAMENT'''
     shortest_distances = np.zeros(len(galaxies))
     for h in range(len(galaxies)):
            distances = np.zeros(len(filament_points))
            for i in range(len(filament_points)):
                  A = filament_points[i][:-4] ; B = filament_points[i][3:-1] ; AB = B - A ; AG = galaxies[h] - A
                  ## OPTIMIZATION STEP 
                  if np.any(AG > 10) or np.any(AG < -10):
                        distances[i] = 100
                        continue
                  # get norm -- in old code had to check if AB == 0 
                  u = A / np.linalg.norm(A)
                  #if statements to check separate cases
                  if np.dot(AG, u) < 0:
                        distances[i] = np.linalg.norm(galaxies[h] - A)
                  elif np.dot(AG, u) > np.linalg.norm(AB):
                        distances[i] = np.linalg.norm(galaxies[h] - B)
                  elif np.dot(AG, u) < np.linalg.norm(AB):
                        distances[i] = np.linalg.norm((np.cross((A-B), (A-galaxies[h])))) / (np.linalg.norm(galaxies[h]-B))
            shortest_distances[h] = np.min(distances)
     return shortest_distances

In [596]:
galfildist3(gals, dfarray)

array([0.21446946, 0.        , 0.        , 0.73704407, 0.        ,
       0.        , 0.        , 0.94088005, 0.        , 0.        ,
       3.92853046, 0.31745262, 0.        , 0.        , 7.63870861,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [1]:
dfarray

NameError: name 'dfarray' is not defined

In [607]:
if np.any(dfarray[0] < 1):
    print('hi')

hi
