In [2]:
%matplotlib inline

import numpy as np

import matplotlib.pyplot as plt
import matplotlib
from mpl_toolkits import mplot3d
from matplotlib import cm
import mpl_toolkits.mplot3d.art3d as art3d

import os
import pandas as pd


matplotlib.rcParams['font.family'] = [ 'serif']
matplotlib.rcParams['agg.path.chunksize'] = 10000

import sys  
sys.path.insert(0, '/Users/Daniel/Documents/Research Projects/Cosmic Filaments/example_filaments')
import read_fils as rf

sys.path.insert(0, '/Users/Daniel/Documents/Research Projects/Cosmic Filaments/Filament_Metrics' )
import fil_metrics.metric_functions as fm #.metric_functions tells which py file to import 

skeleton_file_dm = '/Users/Daniel/Documents/Research Projects/Cosmic Filaments/example_filaments/del_galaxy.NDnet_s5.up.NDskl.BRK.a.NDskl'
filaments_dm = rf.ReadFilament(skeleton_file_dm)
filament_dm_dict = filaments_dm.filament_dict
print(filament_dm_dict) 

#separate 'filaments' and 'critical_points' dictionaries (each is now a list of dictionaries)
fils = filament_dm_dict['filaments'] ; crit_points = filament_dm_dict['critical_points'] 
voids = fm.dict_slice(crit_points, 'cp_idx',0)

header1, ANDSKEL

ndims, 3

Comments, #No comments (RB)

Bounding box, BBOX [-9.46958,-11.2398,-10.2952] [19.1849,19.2268,23.9453]

ncrit, 142
nfils, 90
Reading data fields:
CP field: persistence_ratio

CP field: persistence_nsigmas

CP field: persistence

CP field: persistence_pair

CP field: parent_index

CP field: parent_log_index

CP field: log_field_value

CP field: field_value

CP field: cell

Filament field: field_value

Filament field: orientation

Filament field: cell

Filament field: log_field_value

Filament field: type

Reading filaments took 0.00 secs.
{'ncrit': 142, 'critical_points': [{'cp_idx': 3.0, 'px': 5.24243, 'py': 0.603427, 'pz': 6.55434, 'pair_ID': 29.0, 'boundary': 0.0, 'nfil': 3, 'destID,filID': [[49, 48], [67, 66], [70, 69]], 'Field Vals': [649.3622, 5.034659, 10623.39, 29.0, 2.0, 2.0, 4.026932, 10639.77, 19.0]}, {'cp_idx': 3.0, 'px': 5.72685, 'py': -3.57222, 'pz': 3.31045, 'pair_ID': 18.0, 'boundary': 0.0, 'nfil': 4, 'destID,filID': [[23, 12], [24, 13], [24, 

#### CHECK HOW THIS WORKS WITH CLASSES ####

In [3]:
#Check Filament_Half_Distances class
fils

[{'cp1_idx': 15.0,
  'cp2_idx': 12.0,
  'nsamp': 10,
  'px,py,pz': [[-2.81356, -2.00726, -1.79707],
   [-3.34829, -2.21085, -2.10106],
   [-3.55129, -2.20702, -2.52764],
   [-3.54704, -2.07235, -2.75681],
   [-3.62038, -2.03417, -2.75514],
   [-3.9371, -2.2373, -2.73826],
   [-4.38406, -2.60411, -2.52365],
   [-4.64688, -2.84577, -2.42487],
   [-4.78, -2.92492, -2.53663],
   [-4.79659, -2.93978, -2.5334]],
  'Field Vals': [4.293599, 1.0, 233.1, 0.6328215, 2.0]},
 {'cp1_idx': 15.0,
  'cp2_idx': 6.0,
  'nsamp': 7,
  'px,py,pz': [[-2.81356, -2.00726, -1.79707],
   [-2.42291, -1.79406, -1.743],
   [-2.6088, -2.04234, -0.950936],
   [-2.54813, -2.10565, -0.169142],
   [-2.14741, -1.74321, -0.0415953],
   [-1.84651, -1.46575, 0.0886922],
   [-1.82022, -1.45434, 0.119345]],
  'Field Vals': [4.293599, 1.0, 459.1, 0.738786, 2.0]},
 {'cp1_idx': 16.0,
  'cp2_idx': 17.0,
  'nsamp': 8,
  'px,py,pz': [[0.0720867, -5.67172, 2.83266],
   [0.823442, -5.41287, 3.5961],
   [0.486821, -5.25539, 4.66427],


In [3]:
#check nested function
fm.Fil_Coordinates(fils) #voila it works

[array([[-2.81356, -2.00726, -1.79707],
        [-3.34829, -2.21085, -2.10106],
        [-3.55129, -2.20702, -2.52764],
        [-3.54704, -2.07235, -2.75681],
        [-3.62038, -2.03417, -2.75514],
        [-3.9371 , -2.2373 , -2.73826],
        [-4.38406, -2.60411, -2.52365],
        [-4.64688, -2.84577, -2.42487],
        [-4.78   , -2.92492, -2.53663],
        [-4.79659, -2.93978, -2.5334 ]]),
 array([[-2.81356  , -2.00726  , -1.79707  ],
        [-2.42291  , -1.79406  , -1.743    ],
        [-2.6088   , -2.04234  , -0.950936 ],
        [-2.54813  , -2.10565  , -0.169142 ],
        [-2.14741  , -1.74321  , -0.0415953],
        [-1.84651  , -1.46575  ,  0.0886922],
        [-1.82022  , -1.45434  ,  0.119345 ]]),
 array([[ 0.0720867, -5.67172  ,  2.83266  ],
        [ 0.823442 , -5.41287  ,  3.5961   ],
        [ 0.486821 , -5.25539  ,  4.66427  ],
        [ 0.720634 , -5.33619  ,  4.65914  ],
        [ 1.15715  , -5.39709  ,  4.85646  ],
        [ 1.86223  , -5.60071  ,  5.30492  ]

In [4]:
fm.Fil_Half_Distances(fils)

array([3.04622387, 3.11229748, 4.46305645, 4.31058284, 0.96027399,
       0.05732654, 1.88053861, 1.54317677, 2.1922261 , 0.23506413,
       0.05081504, 1.7629589 , 0.90200784, 0.51346064, 0.35515462,
       3.06344187, 0.95560629, 0.82731707, 0.31235585, 0.65514096,
       2.75730762, 1.32457549, 0.0382706 , 2.22068264, 3.62302728,
       2.87476416, 0.75524065, 0.98301088, 0.64256679, 0.05252   ,
       6.88707645, 2.27856971, 0.20556402, 2.26929474, 2.0326806 ,
       1.42791874, 2.77129877, 2.32362872, 0.44666928, 1.67324322,
       4.55451502, 1.76486823, 0.0846577 , 1.64030069, 0.01740626,
       1.39306017, 1.88171531, 0.20585043, 0.54264338, 0.30794771,
       1.47077178, 1.97264631, 1.22924966, 0.94370155, 4.03172616,
       4.4398585 , 8.40024685, 2.13208575, 0.05251114, 0.01278757,
       2.50528609, 0.02852885, 0.1674365 , 0.0282452 , 2.6269954 ,
       5.36220099, 0.24077643, 0.10308556, 7.67594582, 0.2707358 ,
       0.04619664, 0.17286447, 0.0382701 , 6.20564963, 0.82336

In [3]:
F = fm.Filament_Half_Distances(fils)
f = F.coordinates()
f

[array([[-2.81356, -2.00726, -1.79707],
        [-3.34829, -2.21085, -2.10106],
        [-3.55129, -2.20702, -2.52764],
        [-3.54704, -2.07235, -2.75681],
        [-3.62038, -2.03417, -2.75514],
        [-3.9371 , -2.2373 , -2.73826],
        [-4.38406, -2.60411, -2.52365],
        [-4.64688, -2.84577, -2.42487],
        [-4.78   , -2.92492, -2.53663],
        [-4.79659, -2.93978, -2.5334 ]]),
 array([[-2.81356  , -2.00726  , -1.79707  ],
        [-2.42291  , -1.79406  , -1.743    ],
        [-2.6088   , -2.04234  , -0.950936 ],
        [-2.54813  , -2.10565  , -0.169142 ],
        [-2.14741  , -1.74321  , -0.0415953],
        [-1.84651  , -1.46575  ,  0.0886922],
        [-1.82022  , -1.45434  ,  0.119345 ]]),
 array([[ 0.0720867, -5.67172  ,  2.83266  ],
        [ 0.823442 , -5.41287  ,  3.5961   ],
        [ 0.486821 , -5.25539  ,  4.66427  ],
        [ 0.720634 , -5.33619  ,  4.65914  ],
        [ 1.15715  , -5.39709  ,  4.85646  ],
        [ 1.86223  , -5.60071  ,  5.30492  ]

In [4]:
G = fm.Filament_Half_Distances2(f)
G.half_distances()

NameError: name 'MyDistance' is not defined